### PR TITLE
index the text of the rights statement

### PR DESCRIPTION
**Pull request by csyversen**
fixes https://github.com/nulib/next-generation-repository/issues/604

### CODE REVIEW

**Comment by kdid** [comment]
Are you doing license separately?

**Comment by csyversen** [comment]
@kdid i might as well tack it onto this PR too, i'll give you a heads up when it's done

**Comment by csyversen** [comment]
@kdid cool, submitted! https://github.com/nulib/common-indexer/pull/3

**Comment by kdid** [comment]
License works OK, but Rights Statement throws this when running the elasticsearch init rake task or saving a work. (I merged your common indexer PR and am using master)

```
Common Indexing failure: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [rights_statement]"}],"type":"mapper_parsing_exception","reason":"failed to parse [rights_statement]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:2422"}},"status":400}
```

**Comment by csyversen** [comment]
it's working for me and i just wiped out my index in elastic search and reran the rake task. I'll drop over in a minute!

**Comment by kdid** [comment]
At this point, if you rebase you should be good to go.

**Pull request merged**
